# Generated by Django 3.0.4 on 2023-01-21 17:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20230110_2046'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-fecha_publicacion']},
        ),
        migrations.AddField(
            model_name='post',
            name='estado',
            field=models.CharField(choices=[('DF', 'Borrador'), ('PB', 'Publicado')], default='DF', max_length=2),
        ),
        migrations.AddField(
            model_name='post',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='post',
            name='fecha_publicacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='post',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-fecha_publicacion'], name='post_post_fecha_p_36138c_idx'),
        ),
    ]
